"""Explicit Phase 2A plan generation and execution preflight checks."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from biolab_copilot.contracts import (
    AnalysisPlan,
    DescriptiveStatisticName,
    ImportResult,
    IssueSeverity,
    ValidationIssue,
)
from biolab_copilot.ingestion import sha256_file

PHASE2A_STATISTICS: list[DescriptiveStatisticName] = [
    "n_measurements",
    "mean",
    "median",
    "min",
    "max",
    "sample_sd",
]
PHASE2A_CONFIRMATION_CODES = {
    "DUPLICATE_COMPLETE_RECORD",
    "REPLICATE_TYPE_UNKNOWN",
    "SINGLE_OBSERVATION_GROUP",
}


@dataclass(frozen=True)
class ExecutionPreflight:
    """Validated inputs for one Phase 2A execution attempt."""

    plan: AnalysisPlan
    import_result: ImportResult | None
    plan_sha256: str
    issues: tuple[ValidationIssue, ...]


def _issue(
    code: str,
    message: str,
    suggested_action: str,
    *,
    location: str = "analysis_plan",
    severity: IssueSeverity = IssueSeverity.BLOCKING,
    field: str | None = None,
    raw_value: Any = None,
) -> ValidationIssue:
    safe_raw = None if raw_value is None else str(raw_value)[:200]
    return ValidationIssue(
        code=code,
        severity=severity,
        message=message,
        location=location,
        suggested_action=suggested_action,
        field=field,
        raw_value=safe_raw,
    )


def required_confirmation_codes(import_result: ImportResult) -> list[str]:
    """Return stable warning codes that require explicit plan acknowledgement."""

    codes = {
        issue.code
        for issue in import_result.validation_issues
        if issue.severity == IssueSeverity.WARNING
        and issue.code in PHASE2A_CONFIRMATION_CODES
    }
    return sorted(codes)


def declared_measurement_units(import_result: ImportResult) -> dict[str, str]:
    """Encode the declared generic measurement unit without converting it."""

    values = import_result.dataset_profile.unit_values.get("unit", [])
    if not values:
        return {}
    if len(values) == 1:
        return {"measurement": values[0]}
    return {"measurement": "mixed:" + "|".join(sorted(values))}


def build_analysis_plan(
    input_artifact_path: Path,
    import_result: ImportResult,
    *,
    generated_at: datetime | None = None,
) -> AnalysisPlan:
    """Build an unconfirmed generic-grouped measurement-level plan."""

    if import_result.experiment_type != "generic_grouped":
        raise ValueError("Phase 2A supports only the generic_grouped experiment type.")
    input_artifact_path = input_artifact_path.resolve()
    input_artifact_hash = sha256_file(input_artifact_path)
    required_codes = required_confirmation_codes(import_result)
    return AnalysisPlan(
        plan_id=f"plan-{input_artifact_hash[:16]}",
        experiment_id=import_result.dataset_profile.dataset_id,
        assay_type="generic_grouped",
        objectives=["Describe measurement-row distributions by group."],
        requested_outputs=["analysis_result", "analysis_issues", "run_manifest"],
        configuration=import_result.parse_configuration,
        confirmed=False,
        input_artifact_path=str(input_artifact_path),
        input_artifact_sha256=input_artifact_hash,
        source_sha256=import_result.input_file.sha256,
        column_mapping=import_result.column_mapping,
        declared_units=declared_measurement_units(import_result),
        group_field="group",
        measurement_field="measurement",
        analysis_level="measurement_rows",
        statistics=PHASE2A_STATISTICS,
        sample_sd_ddof=1,
        duplicate_record_policy="retain_and_include_all",
        missing_value_policy="required_measurements_must_be_present",
        outlier_policy="preserve_and_do_not_detect",
        imputation_policy="forbidden",
        transformation_policy="forbidden",
        unit_conversion_policy="forbidden",
        required_confirmations=required_codes,
        warning_confirmations={code: False for code in required_codes},
        generated_at=generated_at or datetime.now(UTC),
    )


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_plan(path: Path) -> tuple[AnalysisPlan | None, list[ValidationIssue]]:
    try:
        plan = AnalysisPlan.model_validate(_load_json(path))
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        return None, [
            _issue(
                "ANALYSIS_PLAN_INVALID",
                f"The analysis plan could not be validated: {type(exc).__name__}.",
                "Provide a JSON file generated by the plan command and preserve it unchanged.",
                location=f"file={path.name}",
            )
        ]
    return plan, []


def _load_import_result(path: Path) -> tuple[ImportResult | None, list[ValidationIssue]]:
    try:
        result = ImportResult.model_validate(_load_json(path))
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        return None, [
            _issue(
                "INPUT_ARTIFACT_INVALID",
                f"The Phase 1 import artifact could not be validated: {type(exc).__name__}.",
                "Use an unchanged imported_data.json produced by the Phase 1 CLI.",
                location=f"file={path.name}",
            )
        ]
    return result, []


def validate_execution_inputs(
    plan_path: Path,
    confirmed_plan_sha256: str,
    *,
    allowed_root: Path | None = None,
) -> ExecutionPreflight:
    """Revalidate the plan, its explicit hash confirmation, and its bound input."""

    plan_hash = sha256_file(plan_path)
    plan, issues = _load_plan(plan_path)
    if plan is None:
        return ExecutionPreflight(
            plan=AnalysisPlan(
                plan_id="invalid-plan",
                experiment_id="invalid-plan",
                assay_type="generic_grouped",
                objectives=["Invalid plan diagnostic"],
            ),
            import_result=None,
            plan_sha256=plan_hash,
            issues=tuple(issues),
        )

    if confirmed_plan_sha256.lower() != plan_hash:
        issues.append(
            _issue(
                "PLAN_HASH_MISMATCH",
                "The explicitly confirmed plan SHA-256 does not match the current plan file.",
                "Recalculate the plan file SHA-256 and explicitly confirm that exact value.",
                raw_value=confirmed_plan_sha256,
            )
        )
    if not plan.confirmed:
        issues.append(
            _issue(
                "PLAN_NOT_CONFIRMED",
                "The plan file is not marked as explicitly confirmed.",
                "Review the plan, set confirmed=true, and then confirm the resulting file hash.",
                field="confirmed",
            )
        )
    if plan.assay_type != "generic_grouped":
        issues.append(
            _issue(
                "UNSUPPORTED_PHASE2A_ASSAY",
                "Phase 2A descriptive statistics support only generic_grouped.",
                "Use the generic_grouped Phase 2A workflow; ELISA remains out of scope.",
                field="assay_type",
                raw_value=plan.assay_type,
            )
        )
    if plan.analysis_level != "measurement_rows":
        issues.append(
            _issue(
                "UNSUPPORTED_ANALYSIS_LEVEL",
                "Phase 2A requires analysis_level=measurement_rows.",
                "Use the measurement_rows level without aggregation or deduplication.",
                field="analysis_level",
                raw_value=plan.analysis_level,
            )
        )
    if list(plan.statistics) != PHASE2A_STATISTICS:
        issues.append(
            _issue(
                "UNSUPPORTED_STATISTICS_SET",
                "The plan statistics do not exactly match the Phase 2A descriptive set.",
                "Use n_measurements, mean, median, min, max, and sample_sd only.",
                field="statistics",
                raw_value=plan.statistics,
            )
        )
    policy_values = {
        "sample_sd_ddof": plan.sample_sd_ddof,
        "duplicate_record_policy": plan.duplicate_record_policy,
        "missing_value_policy": plan.missing_value_policy,
        "outlier_policy": plan.outlier_policy,
        "imputation_policy": plan.imputation_policy,
        "transformation_policy": plan.transformation_policy,
        "unit_conversion_policy": plan.unit_conversion_policy,
    }
    expected_policies = {
        "sample_sd_ddof": 1,
        "duplicate_record_policy": "retain_and_include_all",
        "missing_value_policy": "required_measurements_must_be_present",
        "outlier_policy": "preserve_and_do_not_detect",
        "imputation_policy": "forbidden",
        "transformation_policy": "forbidden",
        "unit_conversion_policy": "forbidden",
    }
    if policy_values != expected_policies:
        issues.append(
            _issue(
                "UNSUPPORTED_ANALYSIS_POLICY",
                "The plan changes a Phase 2A preservation or deterministic-statistics policy.",
                "Use the generated Phase 2A policies without modification.",
                field="configuration",
                raw_value=policy_values,
            )
        )

    import_result: ImportResult | None = None
    if plan.input_artifact_path is None or plan.input_artifact_sha256 is None:
        issues.append(
            _issue(
                "PLAN_INPUT_BINDING_MISSING",
                "The plan does not bind an input artifact path and SHA-256.",
                "Regenerate the plan from a Phase 1 imported_data.json artifact.",
            )
        )
    else:
        input_path = Path(plan.input_artifact_path)
        resolved_input_path = input_path.resolve()
        if allowed_root is not None:
            try:
                resolved_input_path.relative_to(allowed_root.resolve())
            except ValueError:
                issues.append(
                    _issue(
                        "INPUT_ARTIFACT_OUTSIDE_PROJECT",
                        "The plan points to an input artifact outside the project directory.",
                        "Use a project-local Phase 1 import artifact; no outside files are read.",
                        location=f"file={input_path}",
                    )
                )
                resolved_input_path = input_path
        if not resolved_input_path.is_file():
            issues.append(
                _issue(
                    "INPUT_ARTIFACT_NOT_FOUND",
                    "The input import artifact is not available at the path bound by the plan.",
                    "Use the unchanged Phase 1 imported_data.json referenced by the plan.",
                    location=f"file={resolved_input_path}",
                )
            )
        elif not any(issue.code == "INPUT_ARTIFACT_OUTSIDE_PROJECT" for issue in issues):
            actual_artifact_hash = sha256_file(resolved_input_path)
            if actual_artifact_hash != plan.input_artifact_sha256:
                issues.append(
                    _issue(
                        "INPUT_ARTIFACT_HASH_MISMATCH",
                        "The bound Phase 1 import artifact changed after plan generation.",
                        "Regenerate and reconfirm the analysis plan for the changed artifact.",
                        raw_value=actual_artifact_hash,
                    )
                )
            import_result, import_issues = _load_import_result(resolved_input_path)
            issues.extend(import_issues)

    if import_result is not None:
        actual_required_codes = required_confirmation_codes(import_result)
        if list(plan.required_confirmations) != actual_required_codes:
            issues.append(
                _issue(
                    "PLAN_CONFIRMATION_SET_MISMATCH",
                    "The plan confirmation set does not match the current import warnings.",
                    (
                        "Regenerate the plan from the unchanged import artifact and review "
                        "each warning."
                    ),
                    field="required_confirmations",
                    raw_value=actual_required_codes,
                )
            )
        for code in actual_required_codes:
            if plan.warning_confirmations.get(code) is not True:
                issues.append(
                    _issue(
                        "REQUIRED_WARNING_NOT_CONFIRMED",
                        f"Warning {code} has not received explicit confirmation.",
                        "Set the corresponding warning_confirmations value to true after review.",
                        field=f"warning_confirmations.{code}",
                    )
                )
        blocking_import_issues = [
            issue
            for issue in import_result.validation_issues
            if issue.severity in {IssueSeverity.ERROR, IssueSeverity.BLOCKING}
        ]
        if blocking_import_issues or not import_result.analysis_ready:
            issues.append(
                _issue(
                    "IMPORT_QC_NOT_READY",
                    "The Phase 1 import contains an error/blocking issue or is not analysis-ready.",
                    "Resolve the Phase 1 structural QC issues and create a new import artifact.",
                    location="import_result.dataset_profile",
                )
            )
        if import_result.experiment_type != "generic_grouped":
            issues.append(
                _issue(
                    "UNSUPPORTED_INPUT_ASSAY",
                    "The bound import artifact is not generic_grouped.",
                    "Use a generic_grouped Phase 1 import artifact; ELISA is not supported here.",
                    field="experiment_type",
                    raw_value=import_result.experiment_type,
                )
            )
        if plan.source_sha256 != import_result.input_file.sha256:
            issues.append(
                _issue(
                    "SOURCE_HASH_BINDING_MISMATCH",
                    "The plan source SHA-256 does not match the Phase 1 source hash.",
                    "Regenerate the plan from the same imported_data.json artifact.",
                    field="source_sha256",
                )
            )
        if plan.column_mapping != import_result.column_mapping:
            issues.append(
                _issue(
                    "COLUMN_MAPPING_BINDING_MISMATCH",
                    "The plan column mapping does not match the Phase 1 import artifact.",
                    (
                        "Do not edit mappings after plan generation; regenerate and reconfirm "
                        "the plan."
                    ),
                    field="column_mapping",
                )
            )
        if plan.configuration != import_result.parse_configuration:
            issues.append(
                _issue(
                    "PARSER_CONFIGURATION_BINDING_MISMATCH",
                    "The plan parser configuration does not match the Phase 1 import artifact.",
                    "Regenerate the plan from the unchanged import artifact.",
                    field="configuration",
                )
            )
        if plan.declared_units != declared_measurement_units(import_result):
            issues.append(
                _issue(
                    "UNIT_BINDING_MISMATCH",
                    "The plan declared units do not match the Phase 1 import profile.",
                    "Regenerate the plan; no unit conversion is performed in Phase 2A.",
                    field="declared_units",
                )
            )
        if plan.group_field != "group" or plan.measurement_field != "measurement":
            issues.append(
                _issue(
                    "CANONICAL_FIELD_BINDING_MISMATCH",
                    "Phase 2A requires the generic_grouped group and measurement fields.",
                    "Use group_field=group and measurement_field=measurement.",
                    field="group_field",
                )
            )

    return ExecutionPreflight(
        plan=plan,
        import_result=import_result,
        plan_sha256=plan_hash,
        issues=tuple(issues),
    )


__all__ = [
    "ExecutionPreflight",
    "PHASE2A_CONFIRMATION_CODES",
    "PHASE2A_STATISTICS",
    "build_analysis_plan",
    "declared_measurement_units",
    "required_confirmation_codes",
    "validate_execution_inputs",
]
