"""Restricted, deterministic Phase 2B planning and Welch computation."""

from __future__ import annotations

import json
import math
import platform
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import scipy
from scipy import stats

from biolab_copilot.contracts import (
    AnalysisPlan,
    AnalysisResult,
    ExperimentalUnitsPreview,
    ImportResult,
    IndependentTwoGroupDesign,
    InferentialGroupStats,
    IssueSeverity,
    ValidationIssue,
)
from biolab_copilot.ingestion import sha256_file
from biolab_copilot.statistics.experimental_units import build_experimental_units_preview
from biolab_copilot.statistics.plans import declared_measurement_units

WELCH_LIMITATIONS = [
    "The comparison is restricted to one generic_grouped endpoint and two user-named groups.",
    "Independence is user_declared_not_verified; software does not prove the experimental design.",
    "The analysis level is experimental_units, not biological samples or biological_n.",
    (
        "Welch's calculation minimum is two experimental units per group; this does not "
        "establish adequate power or valid assumptions."
    ),
    (
        "No pairing, repeated-measures, clustering, multiple comparisons, transformation, "
        "imputation, or outlier removal is performed."
    ),
    (
        "The p-value is not the probability that the null hypothesis is true, and the result "
        "does not establish causality or efficacy."
    ),
]


@dataclass(frozen=True)
class WelchPlanBuild:
    """An unconfirmed plan, its preview, and deterministic diagnostics."""

    plan: AnalysisPlan
    preview: ExperimentalUnitsPreview
    issues: tuple[ValidationIssue, ...]


@dataclass(frozen=True)
class WelchExecutionPreflight:
    """Validated Phase 2B inputs, or the complete blocking diagnostic set."""

    plan: AnalysisPlan
    design: IndependentTwoGroupDesign | None
    import_result: ImportResult | None
    preview: ExperimentalUnitsPreview | None
    plan_sha256: str
    issues: tuple[ValidationIssue, ...]


def _issue(
    code: str,
    message: str,
    suggested_action: str,
    *,
    location: str = "analysis_plan",
    severity: IssueSeverity = IssueSeverity.BLOCKING,
    field: str | None = None,
    raw_value: Any = None,
) -> ValidationIssue:
    return ValidationIssue(
        code=code,
        severity=severity,
        message=message,
        location=location,
        suggested_action=suggested_action,
        field=field,
        raw_value=None if raw_value is None else str(raw_value)[:200],
    )


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _invalid_plan() -> AnalysisPlan:
    return AnalysisPlan(
        plan_id="invalid-phase2b-plan",
        experiment_id="invalid-phase2b-plan",
        assay_type="generic_grouped",
        objectives=["Invalid Phase 2B diagnostic placeholder"],
        analysis_level="experimental_units",
        statistics=[],
    )


def _load_plan(path: Path) -> tuple[AnalysisPlan, list[ValidationIssue]]:
    try:
        return AnalysisPlan.model_validate(_load_json(path)), []
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        return _invalid_plan(), [
            _issue(
                "ANALYSIS_PLAN_INVALID",
                f"The Phase 2B analysis plan could not be validated: {type(exc).__name__}.",
                "Use an unchanged plan generated by generate-welch-plan.",
                location=f"file={path.name}",
            )
        ]


def _load_design(path: Path) -> tuple[IndependentTwoGroupDesign | None, list[ValidationIssue]]:
    try:
        return IndependentTwoGroupDesign.model_validate(_load_json(path)), []
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        return None, [
            _issue(
                "DESIGN_DECLARATION_INVALID",
                f"The explicit design declaration could not be validated: {type(exc).__name__}.",
                "Provide all required Phase 2B design fields without relying on inference.",
                location=f"file={path.name}",
            )
        ]


def _load_import(path: Path) -> tuple[ImportResult | None, list[ValidationIssue]]:
    try:
        return ImportResult.model_validate(_load_json(path)), []
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        return None, [
            _issue(
                "INPUT_ARTIFACT_INVALID",
                f"The Phase 1 import artifact could not be validated: {type(exc).__name__}.",
                "Use an unchanged imported_data.json produced by the Phase 1 import CLI.",
                location=f"file={path.name}",
            )
        ]


def _design_plan_fields(design: IndependentTwoGroupDesign) -> dict[str, Any]:
    return {
        "design_type": design.design_type,
        "experimental_unit_description": design.experimental_unit_description,
        "experimental_unit_id_field": design.experimental_unit_id_field,
        "independence_declared": design.independence_declared,
        "independence_rationale": design.independence_rationale,
        "group_a": design.group_a,
        "group_b": design.group_b,
        "technical_repeat_policy": design.technical_repeat_policy,
        "method": design.method,
        "alternative": design.alternative,
        "alpha": design.alpha,
        "confidence_level": design.confidence_level,
        "assumptions_acknowledged": design.assumptions_acknowledged,
    }


def _plan_design_matches(plan: AnalysisPlan, design: IndependentTwoGroupDesign) -> bool:
    return all(getattr(plan, name) == value for name, value in _design_plan_fields(design).items())


def _required_warning_codes(preview: ExperimentalUnitsPreview) -> list[str]:
    return sorted({issue.code for issue in preview.warnings})


def build_welch_plan(
    input_artifact_path: Path,
    design_declaration_path: Path,
    preview_path: Path,
    *,
    generated_at: datetime | None = None,
) -> WelchPlanBuild:
    """Build an unconfirmed two-group plan and persistable unit preview in memory."""

    input_artifact_path = input_artifact_path.resolve()
    design_declaration_path = design_declaration_path.resolve()
    preview_path = preview_path.resolve()
    import_result, import_issues = _load_import(input_artifact_path)
    design, design_issues = _load_design(design_declaration_path)
    issues = [*import_issues, *design_issues]
    if import_result is None or design is None:
        raise ValueError(
            "Cannot build a Phase 2B plan without a valid import and design declaration."
        )
    input_artifact_sha256 = sha256_file(input_artifact_path)
    design_hash = sha256_file(design_declaration_path)
    preview_id = f"preview-welch-{input_artifact_sha256[:12]}-{design_hash[:12]}"
    preview_build = build_experimental_units_preview(
        import_result,
        design,
        preview_id=preview_id,
        input_artifact_sha256=input_artifact_sha256,
    )
    issues.extend(preview_build.issues)
    preview = preview_build.preview
    preview_sha256 = None  # Filled by the CLI after the preview file is written.
    plan = AnalysisPlan(
        plan_id=f"plan-welch-{input_artifact_sha256[:12]}-{design_hash[:12]}",
        experiment_id=import_result.dataset_profile.dataset_id,
        assay_type="generic_grouped",
        objectives=[
            "Compare one measurement endpoint between two explicitly named independent groups."
        ],
        requested_outputs=[
            "analysis_plan",
            "experimental_units",
            "analysis_result",
            "analysis_issues",
            "run_manifest",
        ],
        configuration=import_result.parse_configuration,
        confirmed=False,
        input_artifact_path=str(input_artifact_path),
        input_artifact_sha256=input_artifact_sha256,
        source_sha256=import_result.input_file.sha256,
        column_mapping=import_result.column_mapping,
        declared_units=declared_measurement_units(import_result),
        group_field="group",
        measurement_field="measurement",
        analysis_level="experimental_units",
        statistics=[],
        sample_sd_ddof=1,
        duplicate_record_policy="retain_and_include_all",
        missing_value_policy="required_measurements_must_be_present",
        outlier_policy="preserve_and_do_not_detect",
        imputation_policy="forbidden",
        transformation_policy="forbidden",
        unit_conversion_policy="forbidden",
        required_confirmations=_required_warning_codes(preview),
        warning_confirmations={code: False for code in _required_warning_codes(preview)},
        generated_at=generated_at or datetime.now(UTC),
        **_design_plan_fields(design),
        design_declaration_path=str(design_declaration_path),
        design_declaration_sha256=design_hash,
        experimental_unit_preview_path=str(preview_path),
        preview_sha256=preview_sha256,
    )
    return WelchPlanBuild(plan=plan, preview=preview, issues=tuple(issues))


def validate_welch_execution_inputs(
    plan_path: Path,
    confirmed_plan_sha256: str,
    *,
    allowed_root: Path | None = None,
) -> WelchExecutionPreflight:
    """Revalidate every input, declaration, warning confirmation, and preview binding."""

    plan_sha256 = sha256_file(plan_path)
    plan, issues = _load_plan(plan_path)
    design: IndependentTwoGroupDesign | None = None
    import_result: ImportResult | None = None
    preview: ExperimentalUnitsPreview | None = None
    if confirmed_plan_sha256.lower() != plan_sha256:
        issues.append(
            _issue(
                "PLAN_HASH_MISMATCH",
                "The explicit plan SHA-256 confirmation does not match the current plan file.",
                "Confirm the exact SHA-256 of the unchanged plan file.",
                raw_value=confirmed_plan_sha256,
            )
        )
    if not plan.confirmed:
        issues.append(
            _issue(
                "PLAN_NOT_CONFIRMED",
                "The Phase 2B plan is not explicitly marked confirmed.",
                "Review the plan, set confirmed=true and explicitly confirm the resulting SHA-256.",
                field="confirmed",
            )
        )
    if plan.assay_type != "generic_grouped":
        issues.append(
            _issue(
                "UNSUPPORTED_PHASE2B_ASSAY",
                "Phase 2B supports only generic_grouped.",
                "Use a generic_grouped import and Phase 2B plan.",
                field="assay_type",
                raw_value=plan.assay_type,
            )
        )
    if plan.analysis_level != "experimental_units" or plan.statistics:
        issues.append(
            _issue(
                "UNSUPPORTED_PHASE2B_PLAN_LEVEL",
                (
                    "Phase 2B requires analysis_level=experimental_units and no Phase 2A "
                    "statistic set."
                ),
                "Generate a fresh Phase 2B Welch plan; a Phase 2A plan cannot be reused.",
                field="analysis_level",
                raw_value=plan.analysis_level,
            )
        )
    required_design_fields = _design_plan_fields
    if any(
        getattr(plan, name) is None
        for name in required_design_fields(
            IndependentTwoGroupDesign(
                design_type="independent_two_group",
                experimental_unit_description="placeholder",
                experimental_unit_id_field="experimental_unit_id",
                independence_declared=True,
                independence_rationale="placeholder",
                group_a="A",
                group_b="B",
                technical_repeat_policy="none",
                method="welch_t",
                alternative="two-sided",
                alpha=0.05,
                confidence_level=0.95,
                assumptions_acknowledged=True,
            )
        )
    ):
        issues.append(
            _issue(
                "DESIGN_DECLARATION_MISSING",
                "The plan does not contain every required explicit Phase 2B design declaration.",
                (
                    "Regenerate the plan from a complete design declaration; do not infer "
                    "missing fields."
                ),
                field="design_type",
            )
        )
    if plan.independence_declared is not True or plan.assumptions_acknowledged is not True:
        issues.append(
            _issue(
                "DESIGN_ASSUMPTIONS_NOT_ACKNOWLEDGED",
                "The plan must explicitly acknowledge independence and Welch assumptions.",
                (
                    "Provide the required true declarations in the design file and regenerate "
                    "the plan."
                ),
                field="assumptions_acknowledged",
            )
        )

    def resolve_bound_path(raw_path: str | None, *, code: str, label: str) -> Path | None:
        if raw_path is None:
            issues.append(
                _issue(
                    f"{code}_MISSING",
                    f"The plan does not bind a {label} path.",
                    f"Regenerate the Phase 2B plan with a project-local {label}.",
                )
            )
            return None
        path = Path(raw_path).resolve()
        if allowed_root is not None:
            try:
                path.relative_to(allowed_root.resolve())
            except ValueError:
                issues.append(
                    _issue(
                        f"{code}_OUTSIDE_PROJECT",
                        f"The plan points to a {label} outside the project directory.",
                        f"Use a project-local {label}; no outside files are read.",
                        location=f"file={path}",
                    )
                )
                return None
        if not path.is_file():
            issues.append(
                _issue(
                    f"{code}_NOT_FOUND",
                    f"The bound {label} is not available.",
                    f"Restore the unchanged bound {label} or generate a new plan.",
                    location=f"file={path}",
                )
            )
            return None
        return path

    design_path = resolve_bound_path(
        plan.design_declaration_path, code="DESIGN_DECLARATION", label="design declaration"
    )
    if design_path is not None:
        actual_design_hash = sha256_file(design_path)
        if plan.design_declaration_sha256 != actual_design_hash:
            issues.append(
                _issue(
                    "DESIGN_DECLARATION_HASH_MISMATCH",
                    "The bound design declaration changed after plan generation.",
                    "Regenerate and reconfirm the Phase 2B plan.",
                    field="design_declaration_sha256",
                    raw_value=actual_design_hash,
                )
            )
        design, design_load_issues = _load_design(design_path)
        issues.extend(design_load_issues)
        if design is not None and not _plan_design_matches(plan, design):
            issues.append(
                _issue(
                    "DESIGN_PLAN_BINDING_MISMATCH",
                    "The design declaration no longer matches the declarations bound in the plan.",
                    "Regenerate the plan from the unchanged design declaration.",
                    field="design_type",
                )
            )

    input_path = resolve_bound_path(
        plan.input_artifact_path, code="INPUT_ARTIFACT", label="Phase 1 import artifact"
    )
    if input_path is not None:
        actual_input_hash = sha256_file(input_path)
        if plan.input_artifact_sha256 != actual_input_hash:
            issues.append(
                _issue(
                    "INPUT_ARTIFACT_HASH_MISMATCH",
                    "The bound Phase 1 import artifact changed after plan generation.",
                    "Regenerate and reconfirm the Phase 2B plan.",
                    field="input_artifact_sha256",
                    raw_value=actual_input_hash,
                )
            )
        import_result, import_load_issues = _load_import(input_path)
        issues.extend(import_load_issues)

    preview_path = resolve_bound_path(
        plan.experimental_unit_preview_path,
        code="EXPERIMENTAL_UNIT_PREVIEW",
        label="experimental-unit preview",
    )
    if preview_path is not None:
        if plan.preview_sha256 != sha256_file(preview_path):
            issues.append(
                _issue(
                    "PREVIEW_HASH_MISMATCH",
                    "The bound experimental-unit preview changed after plan generation.",
                    "Regenerate and reconfirm the Phase 2B plan.",
                    field="preview_sha256",
                )
            )
        try:
            preview = ExperimentalUnitsPreview.model_validate(_load_json(preview_path))
        except (OSError, json.JSONDecodeError, ValueError) as exc:
            issues.append(
                _issue(
                    "EXPERIMENTAL_UNIT_PREVIEW_INVALID",
                    f"The experimental-unit preview could not be validated: {type(exc).__name__}.",
                    "Use the unchanged preview generated with the plan.",
                    location=f"file={preview_path.name}",
                )
            )

    if import_result is not None:
        if import_result.experiment_type != "generic_grouped":
            issues.append(
                _issue(
                    "UNSUPPORTED_INPUT_ASSAY",
                    "Phase 2B does not accept an ELISA or other non-generic input artifact.",
                    "Use generic_grouped only.",
                    field="experiment_type",
                    raw_value=import_result.experiment_type,
                )
            )
        blocking_import = [
            issue
            for issue in import_result.validation_issues
            if issue.severity in {IssueSeverity.ERROR, IssueSeverity.BLOCKING}
        ]
        if blocking_import or not import_result.analysis_ready:
            issues.append(
                _issue(
                    "IMPORT_QC_NOT_READY",
                    "The Phase 1 import contains an error/blocking issue or is not analysis-ready.",
                    "Resolve structural QC issues and generate a new import artifact.",
                    location="import_result.dataset_profile",
                )
            )
        if plan.source_sha256 != import_result.input_file.sha256:
            issues.append(
                _issue(
                    "SOURCE_HASH_BINDING_MISMATCH",
                    "The plan source SHA-256 does not match the Phase 1 source hash.",
                    "Regenerate the plan from the unchanged import artifact.",
                    field="source_sha256",
                )
            )
        if plan.column_mapping != import_result.column_mapping:
            issues.append(
                _issue(
                    "COLUMN_MAPPING_BINDING_MISMATCH",
                    "The plan column mapping does not match the import artifact.",
                    "Regenerate the plan after any mapping change.",
                    field="column_mapping",
                )
            )
        if plan.configuration != import_result.parse_configuration:
            issues.append(
                _issue(
                    "PARSER_CONFIGURATION_BINDING_MISMATCH",
                    "The plan parser configuration does not match the import artifact.",
                    "Regenerate the plan after any parser configuration change.",
                    field="configuration",
                )
            )
        if plan.declared_units != declared_measurement_units(import_result):
            issues.append(
                _issue(
                    "UNIT_BINDING_MISMATCH",
                    "The plan units do not match the Phase 1 import profile.",
                    "Regenerate the plan; no unit conversion is performed.",
                    field="declared_units",
                )
            )

    if design is not None and import_result is not None and plan.input_artifact_sha256:
        preview_build = build_experimental_units_preview(
            import_result,
            design,
            preview_id=preview.preview_id if preview is not None else "recomputed-preview",
            input_artifact_sha256=plan.input_artifact_sha256,
        )
        issues.extend(preview_build.issues)
        if preview is None or preview_build.preview.model_dump(mode="json") != preview.model_dump(
            mode="json"
        ):
            issues.append(
                _issue(
                    "PREVIEW_CONTENT_MISMATCH",
                    (
                        "The preview does not match a fresh deterministic assignment from the "
                        "bound input and design."
                    ),
                    (
                        "Regenerate the preview and plan; do not hand-edit unit assignments "
                        "or aggregation."
                    ),
                    field="experimental_unit_preview_path",
                )
            )
        current_warning_codes = _required_warning_codes(preview_build.preview)
        if plan.required_confirmations != current_warning_codes:
            issues.append(
                _issue(
                    "PLAN_WARNING_SET_MISMATCH",
                    (
                        "The plan warning confirmation set does not match the current "
                        "preview warnings."
                    ),
                    "Regenerate the plan and explicitly review each warning.",
                    field="required_confirmations",
                )
            )
        for code in current_warning_codes:
            if plan.warning_confirmations.get(code) is not True:
                issues.append(
                    _issue(
                        "REQUIRED_WARNING_NOT_CONFIRMED",
                        f"Warning {code} has not received explicit confirmation.",
                        "Set the matching warning_confirmations field to true after review.",
                        field=f"warning_confirmations.{code}",
                    )
                )
        if preview_build.preview.blocking_reasons:
            issues.append(
                _issue(
                    "EXPERIMENTAL_UNIT_PREVIEW_BLOCKED",
                    "The experimental-unit preview contains blocking reasons.",
                    "Resolve unit identity, group, repeat, and QC issues before inference.",
                    location="experimental_units.blocking_reasons",
                )
            )

    return WelchExecutionPreflight(
        plan=plan,
        design=design,
        import_result=import_result,
        preview=preview,
        plan_sha256=plan_sha256,
        issues=tuple(issues),
    )


def _finite_sample_sd(
    values: list[float], *, location: str
) -> tuple[float | None, ValidationIssue | None]:
    if len(values) < 2:
        return None, _issue(
            "MINIMUM_EXPERIMENTAL_UNITS_NOT_MET",
            (
                "Each group requires at least two experimental units for sample SD and "
                "Welch computation."
            ),
            "Provide at least two experimental units per planned group.",
            location=location,
        )
    mean = math.fsum(values) / len(values)
    squared = [(value - mean) ** 2 for value in values]
    variance = math.fsum(squared) / (len(values) - 1)
    sd = math.sqrt(variance)
    if not all(math.isfinite(value) for value in (mean, variance, sd)):
        return None, _issue(
            "NON_FINITE_WELCH_RESULT",
            "A group mean or sample SD became non-finite.",
            (
                "Review finite source values; no imputation, transformation, or overflow "
                "masking is applied."
            ),
            location=location,
        )
    return sd, None


def _failed_result(
    plan: AnalysisPlan,
    plan_sha256: str,
    issues: list[ValidationIssue],
    import_result: ImportResult | None,
    preview: ExperimentalUnitsPreview | None,
) -> AnalysisResult:
    return AnalysisResult(
        result_id=f"result-{uuid.uuid4().hex[:12]}",
        experiment_id=plan.experiment_id,
        plan_id=plan.plan_id,
        status="failed",
        issues=issues,
        analysis_level="experimental_units",
        declared_units=plan.declared_units,
        independent_biological_n=None,
        input_artifact_sha256=plan.input_artifact_sha256,
        source_sha256=import_result.input_file.sha256 if import_result else plan.source_sha256,
        confirmed_plan_sha256=plan_sha256,
        independence_status="user_declared_not_verified" if plan.design_type else None,
        group_a=plan.group_a,
        group_b=plan.group_b,
        method=plan.method,
        alternative=plan.alternative,
        alpha=plan.alpha,
        confidence_level=plan.confidence_level,
        technical_repeat_policy=plan.technical_repeat_policy,
        experimental_unit_summaries=preview.units if preview else [],
        preview_sha256=plan.preview_sha256,
        known_limitations=WELCH_LIMITATIONS,
        statistical_limitations=WELCH_LIMITATIONS,
    )


def compute_welch_result(
    preflight: WelchExecutionPreflight,
) -> AnalysisResult:
    """Compute the pre-confirmed two-group Welch comparison at unit level."""

    issues = list(preflight.issues)
    blocking_issues = [
        issue
        for issue in issues
        if issue.severity in {IssueSeverity.ERROR, IssueSeverity.BLOCKING}
    ]
    if blocking_issues or preflight.import_result is None or preflight.preview is None:
        return _failed_result(
            preflight.plan,
            preflight.plan_sha256,
            issues,
            preflight.import_result,
            preflight.preview,
        )
    preview = preflight.preview
    group_a = [
        unit.aggregated_value for unit in preview.units if unit.group == preflight.plan.group_a
    ]
    group_b = [
        unit.aggregated_value for unit in preview.units if unit.group == preflight.plan.group_b
    ]
    extra_issues: list[ValidationIssue] = []
    if len(group_a) < 2 or len(group_b) < 2:
        extra_issues.append(
            _issue(
                "MINIMUM_EXPERIMENTAL_UNITS_NOT_MET",
                "Each group must contain at least two experimental units before Welch computation.",
                "Provide at least two explicit experimental units per group.",
                location="experimental_units",
            )
        )
    if not all(math.isfinite(value) for value in [*group_a, *group_b]):
        extra_issues.append(
            _issue(
                "NON_FINITE_INPUT_TO_WELCH",
                "A non-finite value reached the Welch calculation boundary.",
                "Resolve the source value; no non-finite value is accepted for inference.",
                location="experimental_units.aggregated_value",
            )
        )
    if extra_issues:
        return _failed_result(
            preflight.plan,
            preflight.plan_sha256,
            [*issues, *extra_issues],
            preflight.import_result,
            preview,
        )

    sd_a, sd_issue_a = _finite_sample_sd(group_a, location=f"group={preflight.plan.group_a!r}")
    sd_b, sd_issue_b = _finite_sample_sd(group_b, location=f"group={preflight.plan.group_b!r}")
    if sd_issue_a is not None or sd_issue_b is not None or sd_a is None or sd_b is None:
        return _failed_result(
            preflight.plan,
            preflight.plan_sha256,
            [*issues, *(issue for issue in (sd_issue_a, sd_issue_b) if issue is not None)],
            preflight.import_result,
            preview,
        )
    mean_a = math.fsum(group_a) / len(group_a)
    mean_b = math.fsum(group_b) / len(group_b)
    mean_difference = mean_a - mean_b
    variance_a = sd_a**2
    variance_b = sd_b**2
    standard_error_squared = variance_a / len(group_a) + variance_b / len(group_b)
    if sd_a == 0 and sd_b == 0:
        extra_issues.append(
            _issue(
                "BOTH_GROUPS_ZERO_VARIANCE",
                (
                    "Both groups have zero variance; Welch standard error and degrees of "
                    "freedom are undefined."
                ),
                (
                    "Do not report p=0 or a successful inferential result; review the "
                    "experimental design and data."
                ),
                location="experimental_units",
            )
        )
    if not math.isfinite(standard_error_squared) or standard_error_squared <= 0:
        extra_issues.append(
            _issue(
                "WELCH_STANDARD_ERROR_INVALID",
                "The Welch standard error is zero or non-finite.",
                "Review finite, non-degenerate experimental-unit values; no fallback test is used.",
                location="experimental_units",
            )
        )
    if extra_issues:
        return _failed_result(
            preflight.plan,
            preflight.plan_sha256,
            [*issues, *extra_issues],
            preflight.import_result,
            preview,
        )

    if sd_a == 0 or sd_b == 0:
        issues.append(
            _issue(
                "ONE_GROUP_ZERO_VARIANCE",
                "One group has zero variance; the Welch result is retained with this warning.",
                "Review the source data and the stated assumptions before interpreting the result.",
                location="experimental_units",
                severity=IssueSeverity.WARNING,
            )
        )
    standard_error = math.sqrt(standard_error_squared)
    numerator = standard_error_squared**2
    denominator = (variance_a / len(group_a)) ** 2 / (len(group_a) - 1) + (
        variance_b / len(group_b)
    ) ** 2 / (len(group_b) - 1)
    degrees_of_freedom = numerator / denominator
    try:
        scipy_result = stats.ttest_ind(
            group_a,
            group_b,
            equal_var=False,
            alternative="two-sided",
            nan_policy="raise",
        )
        t_critical = stats.t.ppf(1 - (preflight.plan.alpha or 0.05) / 2, degrees_of_freedom)
    except (FloatingPointError, OverflowError, ValueError) as exc:
        extra_issues.append(
            _issue(
                "WELCH_COMPUTATION_FAILED",
                f"SciPy Welch computation failed: {type(exc).__name__}.",
                "Review finite experimental-unit values and rerun without changing the source.",
                location="welch_t",
            )
        )
        return _failed_result(
            preflight.plan,
            preflight.plan_sha256,
            [*issues, *extra_issues],
            preflight.import_result,
            preview,
        )
    t_statistic = float(scipy_result.statistic)
    p_value = float(scipy_result.pvalue)
    ci_half_width = t_critical * standard_error
    ci_lower = mean_difference - ci_half_width
    ci_upper = mean_difference + ci_half_width
    result_values = [
        mean_a,
        mean_b,
        mean_difference,
        standard_error,
        degrees_of_freedom,
        t_statistic,
        p_value,
        ci_lower,
        ci_upper,
    ]
    if p_value <= 0:
        extra_issues.append(
            _issue(
                "P_VALUE_UNDERFLOW",
                "The numerical p-value is zero or below the representable range.",
                "Do not report p=0 as a successful result; review the data scale and design.",
                location="welch_t.p_value",
            )
        )
    if not all(math.isfinite(value) for value in result_values):
        extra_issues.append(
            _issue(
                "NON_FINITE_WELCH_RESULT",
                "Welch or confidence-interval computation produced a non-finite result.",
                "Do not serialize a successful result; review finite source values and scale.",
                location="welch_t",
            )
        )
        return _failed_result(
            preflight.plan,
            preflight.plan_sha256,
            [*issues, *extra_issues],
            preflight.import_result,
            preview,
        )
    if extra_issues:
        return _failed_result(
            preflight.plan,
            preflight.plan_sha256,
            [*issues, *extra_issues],
            preflight.import_result,
            preview,
        )
    group_stats = []
    for group_name, values in (
        (preflight.plan.group_a, group_a),
        (preflight.plan.group_b, group_b),
    ):
        group_stats.append(
            InferentialGroupStats(
                group=group_name or "",
                n_measurements=sum(
                    unit.n_measurements for unit in preview.units if unit.group == group_name
                ),
                n_experimental_units=len(values),
                mean=math.fsum(values) / len(values),
                sample_sd=sd_a if group_name == preflight.plan.group_a else sd_b,
                technical_repeat_counts={
                    unit.experimental_unit_id: unit.technical_repeat_count
                    for unit in preview.units
                    if unit.group == group_name
                },
            )
        )
    return AnalysisResult(
        result_id=f"result-{uuid.uuid4().hex[:12]}",
        experiment_id=preflight.import_result.dataset_profile.dataset_id,
        plan_id=preflight.plan.plan_id,
        status="computed",
        issues=[*issues],
        analysis_level="experimental_units",
        declared_units=preflight.plan.declared_units,
        source_record_references={
            group_name: [
                record_number
                for unit in preview.units
                if unit.group == group_name
                for record_number in unit.source_record_numbers
            ]
            for group_name in (preflight.plan.group_a or "", preflight.plan.group_b or "")
        },
        independent_biological_n=None,
        input_artifact_sha256=preflight.plan.input_artifact_sha256,
        source_sha256=preflight.import_result.input_file.sha256,
        confirmed_plan_sha256=preflight.plan_sha256,
        statistical_limitations=WELCH_LIMITATIONS,
        independence_status="user_declared_not_verified",
        group_a=preflight.plan.group_a,
        group_b=preflight.plan.group_b,
        method="welch_t",
        alternative="two-sided",
        alpha=preflight.plan.alpha,
        confidence_level=preflight.plan.confidence_level,
        technical_repeat_policy=preflight.plan.technical_repeat_policy,
        experimental_unit_summaries=preview.units,
        inferential_group_statistics=group_stats,
        mean_difference=mean_difference,
        mean_difference_ci_lower=ci_lower,
        mean_difference_ci_upper=ci_upper,
        t_statistic=t_statistic,
        degrees_of_freedom=degrees_of_freedom,
        p_value=p_value,
        preview_sha256=preflight.plan.preview_sha256,
        known_limitations=WELCH_LIMITATIONS,
    )


def welch_software_versions() -> dict[str, str]:
    """Return versions recorded in every Phase 2B result manifest."""

    return {"python": platform.python_version(), "scipy": scipy.__version__}


__all__ = [
    "WELCH_LIMITATIONS",
    "WelchExecutionPreflight",
    "WelchPlanBuild",
    "build_welch_plan",
    "compute_welch_result",
    "validate_welch_execution_inputs",
    "welch_software_versions",
]
